// Code generated by "stringer -type=SExpType edif.go edif2qmasm.go parse-edif.go qmasm.go walk-sexp.go"; DO NOT EDIT.

package main

import "strconv"

const _SExpType_name = "SymbolStringIntegerList"

var _SExpType_index = [...]uint8{0, 6, 12, 19, 23}

func (i SExpType) String() string {
	if i < 0 || i >= SExpType(len(_SExpType_index)-1) {
		return "SExpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SExpType_name[_SExpType_index[i]:_SExpType_index[i+1]]
}
